[[cuQuantum]]
arch = "x86_64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "79d27156cbf6b4e8c45bb817da952fb76e668baf"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "c1fa8f577b2fec74014cda285a19a723d54f8213c976f5a52c18295da213147c"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.11.0+0/cuQuantum.v25.11.0.x86_64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[cuQuantum]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "666224c72388c7acad8a056751605e9b146297d8"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "8f9906f155df00cc5923b7eb79f05d84d16f9c4b85d1e39665712d027bea37d1"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.11.0+0/cuQuantum.v25.11.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[cuQuantum]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "54a2b3a9209274ad5213f37b349eee85f46dcbdd"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "85868713adbae582a4d661fe9df88b83c527dc09e06e3d882a9960c4cb8395ae"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.11.0+0/cuQuantum.v25.11.0.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[cuQuantum]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "58587af7863263e5fb40261feb0cebfa8faa7d93"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "55a0f69febc5a977bf840675059b53a544fa5afb015982e02a6136c7e82684b0"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.11.0+0/cuQuantum.v25.11.0.aarch64-linux-gnu-cuda+13.0.tar.gz"
