[[cuQuantum]]
arch = "x86_64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "127942e08fa8b54c3eb6e4152baf7a00c8953d91"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "dd78fc33e5833c3a9b597b5d8698b6fd1cb0b17b285fa0e15332241e7568ec20"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.9.0+0/cuQuantum.v25.9.0.x86_64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[cuQuantum]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "f067b6fde6ff80300d5c70f865d49f5754987d41"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "4dbc55a4504cc6f5f45e5d172b0f02d4d936fb9392557490e9b71c05979c793b"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.9.0+0/cuQuantum.v25.9.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[cuQuantum]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "747e0757bc02b9f6c1f4e9883c6fea78ed5f5145"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "11191d474d33e2f5bd039ed280d2149ee733405739641ace9f90d1e9855b1123"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.9.0+0/cuQuantum.v25.9.0.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[cuQuantum]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "af75668d4a4952b0af7cadff243728d94acd09c4"
lazy = true
libc = "glibc"
os = "linux"

    [[cuQuantum.download]]
    sha256 = "e78ae5387856850f789886ceb0c207d477284eaaf17d36c10964a5650d04faaa"
    url = "https://github.com/JuliaBinaryWrappers/cuQuantum_jll.jl/releases/download/cuQuantum-v25.9.0+0/cuQuantum.v25.9.0.aarch64-linux-gnu-cuda+13.0.tar.gz"
